### ISSUE TITLE
java.lang.NoSuchMethodError at ActivityManagerService

### ISSUE THREAD

**Issue by CollegeDev** [CollegeDev/DonkeyGuard#1]
Method not found at the beginning of loading DonkeyGuard:

```
29 июля 2014 г. 17:46:50 UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'cm_i9100-userdebug 4.4.4 KTU84Q 1a50281812 test-keys' with fingerprint 'samsung/GT-I9100/GT-I9100:4.1.2/JZO54K/I9100XWMS2:user/release-keys'
Loading modules from /data/app/eu.donkeyguard-1.apk
Loading class eu.donkeyguard.hooks.MainHook
PowerService ready
PowerService ready
java.lang.NoSuchMethodError:com.android.server.am.ActivityManagerService#main(int)#exact
at de.robv.android.xposed.XposedHelpers.findMethodExa ct(XposedHelpers.java:179)
at de.robv.android.xposed.XposedHelpers.findAndHookMe    thod(XposedHelpers.java:129)
at de.robv.android.xposed.XposedHelpers.findAndHookMe    thod(XposedHelpers.java:136)
at eu.donkeyguard.hooks.MainHook.initZygote(SourceFil e:64)
at de.robv.android.xposed.XposedBridge.loadModule(Xpo sedBridge.java:437)
at de.robv.android.xposed.XposedBridge.loadModules(Xp osedBridge.java:386)
at de.robv.android.xposed.XposedBridge.main(XposedBri dge.java:120)
at dalvik.system.NativeStart.main(Native Method)
```

ROM: CM-11 with Android 4.4.4

**Comment by CollegeDev** [comment]
Method signature (parameters) does not fit with the given one.
Fixed by using regex pattern for method hooking.
