### ISSUE TITLE
ERROR, DoneyGuard is not activated 

### ISSUE THREAD

**Issue by jumcaesar** [CollegeDev/DonkeyGuard#11]
Always get this message if I want to start the app. Framework module is activated. Reboot done, logs cleared. Can anyone help? 
## Here are my saved logs:

18.08.2014 16:55:12 UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'Ultimate PureXT v4.4' with fingerprint 'Sony/LT30p/LT30p:4.3/9.2.A.1.205/Mvv_tg:user/release-keys'
Loading modules from /data/app/org.baole.app.blacklist-1.apk
  Loading class com.anttek.blacklist.xposed.PermissionMod
Loading modules from /data/app/eu.donkeyguard-1.apk
  Loading class eu.donkeyguard.hooks.MainHook
PowerService ready
PowerService ready
OUTER ERROR - can't find class: [com.android.internal.telephony.ims.IsimUiccRecords]. PLATFORM NOT SUPPORTED.
INNER ERROR - can't hook account feature, because class [android.accounts.AccountManagerService] moved. Fix it by using core.
startup values restricting values: softcodedDefaultDeny: [REAL], default privacy mode: [REAL], interceptUntouchedSettings: [false]
flushed cache with default privacy objects. amount: [0]
SettingsServer, InterceptionServer and Management Server started.
grantSignaturePermission: org.baole.app.blacklist
grantSignaturePermission: org.baole.app.blacklist
grantSignaturePermission: org.baole.app.blacklist
grantSignaturePermission: org.baole.app.blacklist
grantSignaturePermission: org.baole.app.blacklist
grantSignaturePermission: org.baole.app.blacklist
SystemReady - SettingsServer - calling from uid: [1000]
SettingsServer - registered receivers
SystemReady - ManagementServer - calling from uid: [1000]
SystemReady - SettingsServer - calling from uid: [1000]
SystemReady - ManagementServer - calling from uid: [1000]
Boot completed
handleLoadPackage: org.baole.app.blacklist
java.lang.NoSuchMethodError: eu.donkeyguard.gui.activities.MainActivity#isModuleActive()#exact
    at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:179)
    at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:129)
    at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136)
    at eu.donkeyguard.hooks.MainHook.handleLoadPackage(SourceFile:261)
    at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
    at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
    at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
    at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
    at android.app.ActivityThread.handleBindApplication(Native Method)
    at android.app.ActivityThread.access$1300(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
    at android.os.Handler.dispatchMessage(Handler.java)
    at android.os.Looper.loop(Looper.java)
    at android.app.ActivityThread.main(ActivityThread.java)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:525)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by CollegeDev** [comment]
Well done, thanks mate!
It was my fault. Should be fixed in v0.5.43
