### ISSUE TITLE
App Crashing on IceCreamSandwich

### ISSUE THREAD

**Issue by IOAyman** [CollegeDev/DonkeyGuard#32]
The module crashes as soon as I open it.

Is Android 4.0.x supported? If not.. yo may consider this a feature request then ;)

Device: Samsung Galaxy S Duos GT-S7562
OS: ICS 4.0.4
Module version: 0.5.55

**Comment by CollegeDev** [comment]
Minimum API Level is 15. Please post some logs, otherwise I'm not able to fix it.

**Comment by IOAyman** [comment]
Here's part of the logcat where the module crashes

```

I/power   (  421): *** acquire_dvfs_lock : lockType : 1  freq : 1008000 
D/PowerManagerService(  421): releaseDVFSLockLocked : remain DVFS_MIN_LIMIT : next : 1008000
D/STATUSBAR-StatusBarManagerService(  421): setSystemUiVisibility(0x0)
D/STATUSBAR-StatusBarManagerService(  421): manageDisableList what=0x0 pkg=WindowManager.LayoutParams
I/power   (  421): *** release_dvfs_lock : lockType : 1 
I/GATE    ( 3839): <GATE-M>DEV_ACTION_COMPLETED</GATE-M>
D/PowerManagerService(  421): releaseDVFSLockLocked : all DVFS_MIN_LIMIT are released 
D/WML_SISO( 3839): InitPasteboardJni
W/SurfaceFlinger(  113): id=23(1) createSurface 0x13723d4 (1x1),1 flag=0
D/libEGL  ( 3839): loaded /system/lib/egl/libGLES_android.so
D/libEGL  ( 3839): loaded /system/lib/egl/libEGL_adreno200.so
D/libEGL  ( 3839): loaded /system/lib/egl/libGLESv1_CM_adreno200.so
D/libEGL  ( 3839): loaded /system/lib/egl/libGLESv2_adreno200.so
E/AlarmManagerService(  421): android_server_AlarmManagerService_set to type=1, 1411226840.159000000
V/AlarmManager(  421): waitForAlarm result :2
I/Adreno200-EGLSUB( 3839): <ConfigWindowMatch:2218>: Format RGBA_8888.
D/memalloc(  113): /dev/pmem: Allocated buffer base:0x41a97000 size:1474560 offset:3010560 fd:48
D/memalloc( 3839): /dev/pmem: Mapped buffer base:0x52cf9000 size:4485120 offset:3010560 fd:109
D/OpenGLRenderer( 3839): Enabling debug mode 0
V/SlidingMenu( 3839): setting padding!
I/ClipboardServiceEx(  421): Send intent for dismiss clipboard dialog inside hideCurrentInputLocked() !
D/AbsListView( 3839): Get MotionRecognitionManager
W/InputManagerService(  421): Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@41fa9ba8 (uid=10059 pid=920)
V/InputManagerService(  421): Starting input on non-focused client mCurClient info is ClientState{42357b68 uid 10137 pid 3839}
D/AbsListView( 3839): Get MotionRecognitionManager
D/AbsListView( 3839): Get MotionRecognitionManager
D/AndroidRuntime( 3839): Shutting down VM
W/dalvikvm( 3839): threadid=1: thread exiting with uncaught exception (group=0x40c29a68)
E/AndroidRuntime( 3839): FATAL EXCEPTION: main
E/AndroidRuntime( 3839): java.lang.NullPointerException
E/AndroidRuntime( 3839):    at eu.donkeyguard.gui.a.a.a(SourceFile:59)
E/AndroidRuntime( 3839):    at eu.donkeyguard.gui.j.f.onCreateView(SourceFile:98)
E/AndroidRuntime( 3839):    at android.support.v4.app.Fragment.performCreateView(SourceFile:1500)
E/AndroidRuntime( 3839):    at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:927)
E/AndroidRuntime( 3839):    at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1104)
E/AndroidRuntime( 3839):    at android.support.v4.app.BackStackRecord.run(SourceFile:682)
E/AndroidRuntime( 3839):    at android.support.v4.app.FragmentManagerImpl.execPendingActions(SourceFile:1467)
E/AndroidRuntime( 3839):    at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(SourceFile:472)
E/AndroidRuntime( 3839):    at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(SourceFile:163)
E/AndroidRuntime( 3839):    at android.support.v4.view.ViewPager.populate(SourceFile:1068)
E/AndroidRuntime( 3839):    at android.support.v4.view.ViewPager.populate(SourceFile:914)
E/AndroidRuntime( 3839):    at android.support.v4.view.ViewPager.onMeasure(SourceFile:1436)
E/AndroidRuntime( 3839):    at android.view.View.measure(View.java:12842)
E/AndroidRuntime( 3839):    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:594)
E/AndroidRuntime( 3839):    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:376)
E/AndroidRuntime( 3839):    at android.view.View.measure(View.java:12842)
E/AndroidRuntime( 3839):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4712)
E/AndroidRuntime( 3839):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
E/AndroidRuntime( 3839):    at android.view.View.measure(View.java:12842)
E/AndroidRuntime( 3839):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4712)
E/AndroidRuntime( 3839):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
E/AndroidRuntime( 3839):    at android.view.View.measure(View.java:12842)
E/AndroidRuntime( 3839):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4712)
E/AndroidRuntime( 3839):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
E/AndroidRuntime( 3839):    at android.view.View.measure(View.java:12842)
E/AndroidRuntime( 3839):    at com.jeremyfeinstein.slidingmenu.lib.CustomViewAbove.onMeasure(SourceFile:456)
E/AndroidRuntime( 3839):    at android.view.View.measure(View.java:12842)
E/AndroidRuntime( 3839):    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:594)
E/AndroidRuntime( 3839):    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:376)
E/AndroidRuntime( 3839):    at android.view.View.measure(View.java:12842)
E/AndroidRuntime( 3839):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4712)
E/AndroidRuntime( 3839):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
E/AndroidRuntime( 3839):    at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2242)
E/AndroidRuntime( 3839):    at android.view.View.measure(View.java:12842)
E/AndroidRuntime( 3839):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1240)
E/AndroidRuntime( 3839):    at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2632)
E/AndroidRuntime( 3839):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 3839):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 3839):    at android.app.ActivityThread.main(ActivityThread.java:4517)
E/AndroidRuntime( 3839):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 3839):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 3839):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:993)
E/AndroidRuntime( 3839):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:760)
E/AndroidRuntime( 3839):    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
E/AndroidRuntime( 3839):    at dalvik.system.NativeStart.main(Native Method)
D/dalvikvm(  421): GC_FOR_ALLOC freed 1897K, 19% free 21448K/26467K, paused 167ms
V/PowerManagerService(  421): Top Most Needs Intelligent Sleep: true
W/PowerManagerService(  421): Timer 0x7->0x3|0x0
D/lights  (  421): write_int /sys/class/leds/button-backlight/brightness = 0
I/PowerManagerService(  421): Ulight 0x7->0x3|0x0
D/PowerManagerService(  421): setLightBrightness : mButtonLight : 0
E/android.os.Debug(  421): !@Dumpstate > dumpstate -k -t -n -z -d -o /data/log/dumpstate_app_error
I/dumpstate( 3867): Check if stand-alone
I/dumpstate( 3867): begin
E/AlarmManagerService(  421): android_server_AlarmManagerService_set to type=1, 1411226841.159000000
V/AlarmManager(  421): waitForAlarm result :2
```

**Comment by CollegeDev** [comment]
I know what's going wrong there, but I need to test something. Please download the apk from release https://github.com/CollegeDev/DonkeyGuard/releases/tag/test-fix-%2332 and report if it works for you.

**Comment by CollegeDev** [comment]
Any news?
