### ISSUE TITLE
Error during exposed installation -  ----------------- Dec 10, 2015 8:09:03 AM UTC Loading Xposed v54 (for Zygote)... Running ROM 'E3' with fingerprint 'GIONEE/GIONEE/E3:4.4.2/KOT49H/1415337560:user/test-keys' Errors during Xposed initialization java.lang.ClassCastException: class android.content.res.XResources doesn't extend class amigo.theme.core.res.GioneeResources 	at de.robv.android.xposed.XposedBridge.cloneToSubclass(XposedBridge.java:787) 	at de.robv.android.xposed.XposedBridge.hookResources(XposedBridge.java:365) 	at de.robv.android.xposed.XposedBridge.initXbridgeZygote(XposedBridge.java:267) 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117) 	at dalvik.system.NativeStart.main(Native Method) 

### ISSUE THREAD

**Issue by zafarsr** [CollegeDev/DonkeyGuard#59]

**Comment by zafarsr** [comment]
Please help me
