### ISSUE TITLE
Error during exposed installation pls help

### ISSUE THREAD

**Issue by zafarsr** [CollegeDev/DonkeyGuard#60]
## Here is the log from framework

Dec 10, 2015 8:09:03 AM UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'E3' with fingerprint 'GIONEE/GIONEE/E3:4.4.2/KOT49H/1415337560:user/test-keys'
Errors during Xposed initialization
java.lang.ClassCastException: class android.content.res.XResources doesn't extend class amigo.theme.core.res.GioneeResources
    at de.robv.android.xposed.XposedBridge.cloneToSubclass(XposedBridge.java:787)
    at de.robv.android.xposed.XposedBridge.hookResources(XposedBridge.java:365)
    at de.robv.android.xposed.XposedBridge.initXbridgeZygote(XposedBridge.java:267)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by shilpamtiwari1** [comment]
Error during exposed installation plz help

Here is log from exposed

---

Dec 27, 2015 1:30:01 AM UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'Intex_Aqua_Pro_V08_Indian_SER' with fingerprint 'Intex/Aqua_Pro/Aqua_Pro:4.4.2/KOT49H/Intex_Aqua_Pro_V08_Indian_SER:user/release-keys'
Errors during Xposed initialization
java.lang.ClassCastException: class android.content.res.XResources doesn't extend class android.content.res.SPRDResources
    at de.robv.android.xposed.XposedBridge.cloneToSubclass(XposedBridge.java:787)
    at de.robv.android.xposed.XposedBridge.hookResources(XposedBridge.java:365)
    at de.robv.android.xposed.XposedBridge.initXbridgeZygote(XposedBridge.java:267)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
    at dalvik.system.NativeStart.main(Native Method)
